version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    links:
      - app
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    links:
      - app
      - prometheus
